//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioClient.GimnacioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://schemas.datacontract.org/2004/07/GimnacioServices")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassId {
            get {
                return this.ClassIdField;
            }
            set {
                if ((this.ClassIdField.Equals(value) != true)) {
                    this.ClassIdField = value;
                    this.RaisePropertyChanged("ClassId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainerId {
            get {
                return this.TrainerIdField;
            }
            set {
                if ((this.TrainerIdField.Equals(value) != true)) {
                    this.TrainerIdField = value;
                    this.RaisePropertyChanged("TrainerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GimnacioServices")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GimnacioService.IClassManager")]
    public interface IClassManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/RegisterClass", ReplyAction="http://tempuri.org/IClassManager/RegisterClassResponse")]
        int RegisterClass(GimnacioClient.GimnacioService.Class newClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/RegisterClass", ReplyAction="http://tempuri.org/IClassManager/RegisterClassResponse")]
        System.Threading.Tasks.Task<int> RegisterClassAsync(GimnacioClient.GimnacioService.Class newClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/ValidateDateIsAvailable", ReplyAction="http://tempuri.org/IClassManager/ValidateDateIsAvailableResponse")]
        int ValidateDateIsAvailable(System.DateTime classDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/ValidateDateIsAvailable", ReplyAction="http://tempuri.org/IClassManager/ValidateDateIsAvailableResponse")]
        System.Threading.Tasks.Task<int> ValidateDateIsAvailableAsync(System.DateTime classDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetClasses", ReplyAction="http://tempuri.org/IClassManager/GetClassesResponse")]
        GimnacioClient.GimnacioService.Class[] GetClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetClasses", ReplyAction="http://tempuri.org/IClassManager/GetClassesResponse")]
        System.Threading.Tasks.Task<GimnacioClient.GimnacioService.Class[]> GetClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetBookClassesByMember", ReplyAction="http://tempuri.org/IClassManager/GetBookClassesByMemberResponse")]
        GimnacioClient.GimnacioService.Class[] GetBookClassesByMember(int IdMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetBookClassesByMember", ReplyAction="http://tempuri.org/IClassManager/GetBookClassesByMemberResponse")]
        System.Threading.Tasks.Task<GimnacioClient.GimnacioService.Class[]> GetBookClassesByMemberAsync(int IdMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetTotalAssistantsToClass", ReplyAction="http://tempuri.org/IClassManager/GetTotalAssistantsToClassResponse")]
        int GetTotalAssistantsToClass(int IdClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/GetTotalAssistantsToClass", ReplyAction="http://tempuri.org/IClassManager/GetTotalAssistantsToClassResponse")]
        System.Threading.Tasks.Task<int> GetTotalAssistantsToClassAsync(int IdClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/BookClass", ReplyAction="http://tempuri.org/IClassManager/BookClassResponse")]
        int BookClass(int classId, int idMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassManager/BookClass", ReplyAction="http://tempuri.org/IClassManager/BookClassResponse")]
        System.Threading.Tasks.Task<int> BookClassAsync(int classId, int idMember);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassManagerChannel : GimnacioClient.GimnacioService.IClassManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassManagerClient : System.ServiceModel.ClientBase<GimnacioClient.GimnacioService.IClassManager>, GimnacioClient.GimnacioService.IClassManager {
        
        public ClassManagerClient() {
        }
        
        public ClassManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegisterClass(GimnacioClient.GimnacioService.Class newClass) {
            return base.Channel.RegisterClass(newClass);
        }
        
        public System.Threading.Tasks.Task<int> RegisterClassAsync(GimnacioClient.GimnacioService.Class newClass) {
            return base.Channel.RegisterClassAsync(newClass);
        }
        
        public int ValidateDateIsAvailable(System.DateTime classDateTime) {
            return base.Channel.ValidateDateIsAvailable(classDateTime);
        }
        
        public System.Threading.Tasks.Task<int> ValidateDateIsAvailableAsync(System.DateTime classDateTime) {
            return base.Channel.ValidateDateIsAvailableAsync(classDateTime);
        }
        
        public GimnacioClient.GimnacioService.Class[] GetClasses() {
            return base.Channel.GetClasses();
        }
        
        public System.Threading.Tasks.Task<GimnacioClient.GimnacioService.Class[]> GetClassesAsync() {
            return base.Channel.GetClassesAsync();
        }
        
        public GimnacioClient.GimnacioService.Class[] GetBookClassesByMember(int IdMember) {
            return base.Channel.GetBookClassesByMember(IdMember);
        }
        
        public System.Threading.Tasks.Task<GimnacioClient.GimnacioService.Class[]> GetBookClassesByMemberAsync(int IdMember) {
            return base.Channel.GetBookClassesByMemberAsync(IdMember);
        }
        
        public int GetTotalAssistantsToClass(int IdClass) {
            return base.Channel.GetTotalAssistantsToClass(IdClass);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalAssistantsToClassAsync(int IdClass) {
            return base.Channel.GetTotalAssistantsToClassAsync(IdClass);
        }
        
        public int BookClass(int classId, int idMember) {
            return base.Channel.BookClass(classId, idMember);
        }
        
        public System.Threading.Tasks.Task<int> BookClassAsync(int classId, int idMember) {
            return base.Channel.BookClassAsync(classId, idMember);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GimnacioService.IUserManager")]
    public interface IUserManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetUser", ReplyAction="http://tempuri.org/IUserManager/GetUserResponse")]
        GimnacioClient.GimnacioService.User GetUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetUser", ReplyAction="http://tempuri.org/IUserManager/GetUserResponse")]
        System.Threading.Tasks.Task<GimnacioClient.GimnacioService.User> GetUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetUserById", ReplyAction="http://tempuri.org/IUserManager/GetUserByIdResponse")]
        GimnacioClient.GimnacioService.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetUserById", ReplyAction="http://tempuri.org/IUserManager/GetUserByIdResponse")]
        System.Threading.Tasks.Task<GimnacioClient.GimnacioService.User> GetUserByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerChannel : GimnacioClient.GimnacioService.IUserManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerClient : System.ServiceModel.ClientBase<GimnacioClient.GimnacioService.IUserManager>, GimnacioClient.GimnacioService.IUserManager {
        
        public UserManagerClient() {
        }
        
        public UserManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GimnacioClient.GimnacioService.User GetUser(string email, string password) {
            return base.Channel.GetUser(email, password);
        }
        
        public System.Threading.Tasks.Task<GimnacioClient.GimnacioService.User> GetUserAsync(string email, string password) {
            return base.Channel.GetUserAsync(email, password);
        }
        
        public GimnacioClient.GimnacioService.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<GimnacioClient.GimnacioService.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
    }
}
